// Song Enrichment Script - Add Genre and Release Year to bndy-songs
// Uses LLM knowledge to enrich existing songs with missing metadata

const AWS = require('aws-sdk');
const dynamodb = new AWS.DynamoDB.DocumentClient({ region: 'eu-west-2' });

// Song enrichment data generated by Claude LLM based on song title + artist
const enrichmentData = {
  "lh52UHKkEyeKSToaEiRJ": { artist: "Kirsty MacColl", title: "A New England", genre: "Alternative Rock", year: 1985 },
  "VyK6JeC14dV12fhWJwS1": { artist: "James", title: "Sit Down", genre: "Alternative Rock", year: 1991 },
  "kFE4OVmaoX2dwqPaQjMy": { artist: "Republica", title: "Ready to Go", genre: "Alternative Rock", year: 1996 },
  "4EnEbQuUs90NWz5kCCLA": { artist: "Muse", title: "Time is Running Out", genre: "Alternative Rock", year: 2003 },
  "NAgcfXokQbK8JquW69Z9": { artist: "Billie Joe Armstrong, Green Day", title: "I Think We're Alone Now", genre: "Rock", year: 1987 },
  "104ea54d-02d7-4f33-b188-35ffb85071ba": { artist: "The Darkness", title: "I Believe in a Thing Called Love", genre: "Rock", year: 2003 },
  "7OtEpYEQWwPKGqi6sETF": { artist: "Radiohead", title: "Creep", genre: "Alternative Rock", year: 1992 },
  "uW1MTjiK3HwSMxnky2kK": { artist: "The Wailers", title: "I Shot The Sheriff", genre: "Reggae", year: 1973 },
  "161a2b10-7382-4126-bcc2-59a175535462": { artist: "Muse", title: "Plug in Baby", genre: "Alternative Rock", year: 2001 },
  "WVDYwtE8Q2AQ8XggENxA": { artist: "Stereophonics", title: "The Bartender And The Thief", genre: "Rock", year: 1998 },
  "1tuKpjmlVsSvSK7SO4S6": { artist: "Baby D", title: "Let Me Be Your Fantasy - Original Radio Edit", genre: "Electronic", year: 1992 },
  "EiukFWPTvEVQTG0O85YI": { artist: "Fleetwood Mac", title: "Albatross", genre: "Rock", year: 1968 },
  "n2rXHpQlwBoZMhpy59N2": { artist: "The Damned", title: "Eloise", genre: "Punk", year: 1986 },
  "ga9JSmiLCdg7HqsY78DX": { artist: "Gloria Gaynor", title: "I Will Survive", genre: "Disco", year: 1978 },
  "9kdm6CJ8sTWXKYyjVPOe": { artist: "Madonna", title: "Like a Prayer", genre: "Pop", year: 1989 },
  "03b5a283-a4d0-42b0-98b9-8426d93b4c29": { artist: "Curiosity Killed The Cat", title: "Down To Earth", genre: "Pop", year: 1986 },
  "ddd6a9e5-a8f3-408b-81a5-8c5cb742f58c": { artist: "Dexys Midnight Runners", title: "Come On Eileen", genre: "Pop", year: 1982 },
  "f1a7d7df-ad05-48a5-ad71-38638de54be2": { artist: "Wham!", title: "Wake Me Up Before You Go-Go", genre: "Pop", year: 1984 },
  "c3645121-d209-45a7-9f46-eb40b883913e": { artist: "Toto", title: "Africa", genre: "Rock", year: 1982 },
  "a2b37954-23e7-46c1-a980-a3e83025f0e6": { artist: "Culture Club", title: "Karma Chameleon", genre: "Pop", year: 1983 },
  "1U5QgrSdvLr05j6Spo00": { artist: "Soft Cell", title: "Tainted Love", genre: "Synth-pop", year: 1981 },
  "1yX1qHGfCMlpmK0kF63C": { artist: "AC/DC", title: "Back In Black", genre: "Rock", year: 1980 },
  "1A8EJuF0TW3UrDCwEJsU": { artist: "The Beatles", title: "Come Together", genre: "Rock", year: 1969 },
  "HYlw4lkwh0Cj5RbdNPc1": { artist: "The Beatles", title: "Day Tripper - Remastered 2015", genre: "Rock", year: 1965 },
  "qyOYqFB5snTMzmjlQXJJ": { artist: "Nirvana", title: "Smells Like Teen Spirit", genre: "Grunge", year: 1991 },
  "YUwWLmZ6f5BDmOI0dUZU": { artist: "Blink-182", title: "All The Small Things", genre: "Pop Punk", year: 1999 },
  "Z5IbJDdKBnxVzxLY7eSG": { artist: "Blur", title: "Song 2", genre: "Alternative Rock", year: 1997 },
  "FxtvHNj1jHs7lmgnvEUY": { artist: "The Clash", title: "Should I Stay or Should I Go", genre: "Punk", year: 1982 },
  "h1kARCGDjSYaM4bR0ypA": { artist: "Elbow", title: "One Day Like This", genre: "Alternative Rock", year: 2008 },
  "YxLkaxALAXYvMRb5OhXn": { artist: "Foo Fighters", title: "Learn to Fly", genre: "Alternative Rock", year: 1999 },
  "m27TGmzWVTaYMJJMt0Vn": { artist: "Foo Fighters", title: "Everlong", genre: "Alternative Rock", year: 1997 },
  "WqKmX0qnSWLBX4T9u89s": { artist: "Guns N' Roses", title: "Sweet Child O' Mine", genre: "Rock", year: 1987 },
  "eiCL4vHqFz4CZK3qxXXE": { artist: "Iggy Pop", title: "The Passenger", genre: "Punk", year: 1977 },
  "M44jVGr2HNJOkRCvq6CR": { artist: "Joy Division", title: "Love Will Tear Us Apart", genre: "Post-Punk", year: 1980 },
  "2qXQpASDSrGAJV4VmfRR": { artist: "Kaiser Chiefs", title: "Ruby", genre: "Indie Rock", year: 2007 },
  "5LrREqFxOxJhTqCd0HdP": { artist: "Kasabian", title: "Fire", genre: "Indie Rock", year: 2009 },
  "FRrCRm45sWy0WXQlEU7c": { artist: "Kings Of Leon", title: "Sex On Fire", genre: "Rock", year: 2008 },
  "zv0bRDvlMOnLsJ0S0hXX": { artist: "Oasis", title: "Wonderwall - Remastered", genre: "Rock", year: 1995 },
  "mJJAyj1Vg1RmcMYkZqZR": { artist: "Oasis", title: "Don't Look Back In Anger - Remastered", genre: "Rock", year: 1995 },
  "hXS4QWxEElvJiKEpQJVW": { artist: "Placebo", title: "Nancy Boy", genre: "Alternative Rock", year: 1996 },
  "DQ3rQPCEQ99HfD9ccgYZ": { artist: "Pulp", title: "Common People", genre: "Britpop", year: 1995 },
  "MmymlWODr6s6R2Vb6z5e": { artist: "Queen", title: "Bohemian Rhapsody - Remastered 2011", genre: "Rock", year: 1975 },
  "EzrpMwDkHVzRHfhsBPCP": { artist: "R.E.M.", title: "Losing My Religion", genre: "Alternative Rock", year: 1991 },
  "tSa9LqVEQ78N4LB4wGjK": { artist: "Red Hot Chili Peppers", title: "Californication", genre: "Alternative Rock", year: 1999 },
  "ZFYi6CRsHviBjr3DT5AR": { artist: "Red Hot Chili Peppers", title: "Under The Bridge", genre: "Alternative Rock", year: 1991 },
  "YDrQxXcLs9iDQ0N0nDw5": { artist: "Stone Roses", title: "I Wanna Be Adored", genre: "Alternative Rock", year: 1989 },
  "pMRY7vRXm39iCG1fFEj7": { artist: "The Killers", title: "Mr. Brightside", genre: "Indie Rock", year: 2003 },
  "MrT3OAUj0MiHmh9Hzm1n": { artist: "The Smiths", title: "This Charming Man - 2011 Remaster", genre: "Indie Rock", year: 1983 },
  "nMNbZF1kKYr5XuLV7wfX": { artist: "The Strokes", title: "Last Nite", genre: "Indie Rock", year: 2001 },
  "U90LfNKAC4J5ygwj7UQT": { artist: "The White Stripes", title: "Seven Nation Army", genre: "Rock", year: 2003 },
  "Z2pNTCmV0oIDEqIQwKzW": { artist: "U2", title: "With Or Without You", genre: "Rock", year: 1987 },
  "KKwXYJNPqpF4BrBxiRPR": { artist: "Arctic Monkeys", title: "I Bet You Look Good On The Dancefloor", genre: "Indie Rock", year: 2005 },
  "TT6vV3z9XiPjTpRcvfQh": { artist: "The Killers", title: "Somebody Told Me", genre: "Indie Rock", year: 2004 },
  "DRdEyFsEYjuUW4OhAWKp": { artist: "Catfish and the Bottlemen", title: "Cocoon", genre: "Indie Rock", year: 2014 },
  "xgT8cT2IZCnvVtI1BfmA": { artist: "David Bowie", title: "Starman - 2012 Remaster", genre: "Rock", year: 1972 },
  "uZpXghyuC8RBXtKJkuYm": { artist: "Jet", title: "Are You Gonna Be My Girl", genre: "Rock", year: 2003 },
  "sSv5Wz3u08xhtM6DqQqP": { artist: "Muse", title: "Supermassive Black Hole", genre: "Alternative Rock", year: 2006 },
  "LH5cOX8qrXsKGNJdyRSF": { artist: "Panic! At The Disco", title: "I Write Sins Not Tragedies", genre: "Pop Punk", year: 2005 },
  "wkZUhPGlTmq8hcDdE7ZE": { artist: "The Zutons", title: "Valerie", genre: "Indie Rock", year: 2006 },
  "k5pLXGdOOXNv0qNOCQ8I": { artist: "Two Door Cinema Club", title: "What You Know", genre: "Indie Rock", year: 2010 },
  "T7yHdOF93pJ3lMh1nYmI": { artist: "The Kooks", title: "Naive", genre: "Indie Rock", year: 2006 },
  "AYGzrYjO3xKqF23qXKvh": { artist: "Bloc Party", title: "Banquet", genre: "Indie Rock", year: 2004 },
  "oWuIVqMkzS7WnvbjBzmA": { artist: "Franz Ferdinand", title: "Take Me Out", genre: "Indie Rock", year: 2004 },
  "TIz0RW9m0mUqKp3yXN5A": { artist: "The Wombats", title: "Let's Dance to Joy Division", genre: "Indie Rock", year: 2007 },
  "g5zRfr6HJxYuLqX16zJH": { artist: "Phoenix", title: "1901", genre: "Indie Pop", year: 2009 },
  "XxLsCQUlW5hVCkQN5sRX": { artist: "Foster The People", title: "Pumped Up Kicks", genre: "Indie Pop", year: 2010 },
  "FJh5kpzxiD3YxNf3hXwV": { artist: "Vampire Weekend", title: "A-Punk", genre: "Indie Rock", year: 2008 },
  "uBKYVUxTvw8sTy2fJIwD": { artist: "The Fratellis", title: "Chelsea Dagger", genre: "Indie Rock", year: 2006 },
  "rkLIj8AhJ9nLXQCQmOKl": { artist: "Tame Impala", title: "Elephant", genre: "Psychedelic Rock", year: 2012 },
  "f8DyvmBbBDfXjzY2Kxri": { artist: "Gorillaz", title: "Feel Good Inc.", genre: "Alternative Rock", year: 2005 },
  "gNQxJLRTxwZ2nfXYE4OU": { artist: "The Hives", title: "Hate To Say I Told You So", genre: "Punk", year: 2000 },
  "Y4X9tHPDGgjkLz3ZfLlw": { artist: "Biffy Clyro", title: "Many of Horror", genre: "Alternative Rock", year: 2010 },
  "kTLF4qcaMyxRjLaIhlQE": { artist: "Interpol", title: "Evil", genre: "Post-Punk", year: 2004 },
  "UR8l9YQsXnUOkfkYnvDe": { artist: "Yeah Yeah Yeahs", title: "Maps", genre: "Indie Rock", year: 2003 },
  "pjFrlpQQnGjsOxRO6nxD": { artist: "Pixies", title: "Where Is My Mind?", genre: "Alternative Rock", year: 1988 },
  "SNUcWQ7yJTyOuPzNJXbV": { artist: "The Libertines", title: "Can't Stand Me Now", genre: "Indie Rock", year: 2004 },
  "H4MQgqr0LpRW2WDWmqmU": { artist: "The Vaccines", title: "If You Wanna", genre: "Indie Rock", year: 2011 },
  "m0rXMWpHyZO1OiqkrWyB": { artist: "Klaxons", title: "Golden Skans", genre: "Indie Rock", year: 2007 },
  "hQgC7rQPIWfXbZO8a4Z4": { artist: "Maximo Park", title: "Apply Some Pressure", genre: "Indie Rock", year: 2005 },
  "cO0AxCwQfzJh68YysPgD": { artist: "Razorlight", title: "America", genre: "Indie Rock", year: 2006 },
  "j1o4IHV8mxQ5vS5RqV47": { artist: "The Enemy", title: "Had Enough", genre: "Indie Rock", year: 2007 },
  "hVxLsKBDkfQVJKN1UUlN": { artist: "The Cribs", title: "Men's Needs", genre: "Indie Rock", year: 2007 },
  "zIkOsNTGDCy1s1o7uZMX": { artist: "Editors", title: "Munich", genre: "Indie Rock", year: 2005 },
  "jMhSYqd7LqHMjmqKlkR6": { artist: "Snow Patrol", title: "Chasing Cars", genre: "Alternative Rock", year: 2006 },
  "Y00lqZlxEORB8iXXu0HI": { artist: "Feeder", title: "Buck Rogers", genre: "Rock", year: 2001 },
  "dmwdBW1cVu2NwBqVQlSJ": { artist: "The Darkness", title: "Growing on Me", genre: "Rock", year: 2003 },
  "oXpgpJ8BZzQCMcRqUKYg": { artist: "The View", title: "Same Jeans", genre: "Indie Rock", year: 2006 },
  "VUXlf7RBDX7NpzmznDH7": { artist: "Razorlight", title: "Golden Touch", genre: "Indie Rock", year: 2004 },
  "pE0yyRgDdvM3RFqX7fxM": { artist: "Athlete", title: "Wires", genre: "Indie Rock", year: 2005 },
  "RNIxjFFvLjr6K4yWVZ5J": { artist: "Hard-Fi", title: "Hard to Beat", genre: "Indie Rock", year: 2005 },
  "DYm3AQ5rUfr5WdPHXpW8": { artist: "The Subways", title: "Rock & Roll Queen", genre: "Rock", year: 2005 },
  "l91NtjENgXqkZf3Bvg2S": { artist: "Kasabian", title: "Club Foot", genre: "Indie Rock", year: 2004 },
  "z5dPZiLEBDLwZmWDvwPH": { artist: "The Coral", title: "Dreaming Of You", genre: "Indie Rock", year: 2002 },
  "uMpEhlTYUCmA8C9KBiQF": { artist: "The Courteeners", title: "Not Nineteen Forever", genre: "Indie Rock", year: 2007 },
  "1eU5qBG7mhbh3TZl9m7o": { artist: "Kaiser Chiefs", title: "I Predict A Riot", genre: "Indie Rock", year: 2004 },
  "FhIhJ3Yy1KDQ0SVhE8Ba": { artist: "Supergrass", title: "Alright", genre: "Britpop", year: 1995 },
  "Bk8kKvFr0hh0v28Z2Zg5": { artist: "Ash", title: "Girl From Mars", genre: "Rock", year: 1995 },
  "N2VPnC4UJf0MKoXvPgLQ": { artist: "Elastica", title: "Connection", genre: "Britpop", year: 1994 },
  "U6QNyUwLKL7qBLZ2cFcH": { artist: "Ocean Colour Scene", title: "The Day We Caught The Train", genre: "Britpop", year: 1996 },
  "Kt0t9nw1sL4cPdwqMQPf": { artist: "Cast", title: "Walk Away", genre: "Britpop", year: 1996 },
  "vkdKQlRxqQ31YRXLcwVD": { artist: "Shed Seven", title: "Chasing Rainbows", genre: "Britpop", year: 1996 },
  "YT1lQ5K5RyRwz5SaXtZN": { artist: "Gene", title: "Olympian", genre: "Britpop", year: 1995 },
  "CkULyEOmPqfIwS3oHhVe": { artist: "The Verve", title: "Bitter Sweet Symphony", genre: "Alternative Rock", year: 1997 },
  "XaL4iCn6zFLQC3CQwFwg": { artist: "Manic Street Preachers", title: "A Design for Life", genre: "Alternative Rock", year: 1996 },
  "2tLPwLGkdPtR5Xb5rjsH": { artist: "Suede", title: "Beautiful Ones", genre: "Britpop", year: 1996 },
  "sXJ0F0EfYZ8dXHKNY3aM": { artist: "The Charlatans", title: "One to Another", genre: "Alternative Rock", year: 1996 },
  "wq2F5nLdxIrRFxvQD4tN": { artist: "Dodgy", title: "Good Enough", genre: "Britpop", year: 1996 },
  "1iKWAE7dNL6I2xNPJ4YZ": { artist: "Sleeper", title: "Sale of the Century", genre: "Britpop", year: 1996 },
  "QvUqIKITF3UQK3lCk7YP": { artist: "Space", title: "Female of the Species", genre: "Alternative Rock", year: 1996 },
  "oGBjUILMC3FQJcMUlEpL": { artist: "James", title: "Laid", genre: "Alternative Rock", year: 1993 },
  "lSc9jFqEEhc8D76k8u8B": { artist: "Therapy?", title: "Screamager", genre: "Alternative Rock", year: 1993 },
  "KUYXXGllFuK8T2jE7KJv": { artist: "Reef", title: "Place Your Hands", genre: "Rock", year: 1996 },
  "WllXAEjRjxMLCpjN3FKD": { artist: "Shed Seven", title: "Going For Gold", genre: "Britpop", year: 1996 },
  "7M6u48c4xO7b5qfpPQgG": { artist: "Marion", title: "Sleep", genre: "Britpop", year: 1995 },
  "pQHNlyXxIqPuBHs5aBWY": { artist: "Mansun", title: "Wide Open Space", genre: "Alternative Rock", year: 1997 },
  "YYhbvhhCnMCfmMmhYHYv": { artist: "Black Grape", title: "Reverend Black Grape", genre: "Alternative Rock", year: 1995 },
  "XkgdR0qxTfJYgLmf2eU2": { artist: "The Lightning Seeds", title: "Three Lions", genre: "Pop", year: 1996 },
  "TH7i1SfpIp5TjFZWg0wA": { artist: "The Beautiful South", title: "Don't Marry Her", genre: "Pop", year: 1996 },
  "ZySzV1uOLrJYqyfjAQ1g": { artist: "The Boo Radleys", title: "Wake Up Boo!", genre: "Britpop", year: 1995 },
  "QG5DcmPE5v5XnSX7Ggb5": { artist: "Echobelly", title: "Great Things", genre: "Britpop", year: 1995 },
  "Yjjj8hFm5vWPd8bQHqQC": { artist: "Catatonia", title: "Mulder and Scully", genre: "Britpop", year: 1998 },
  "pjOTQWE9JJB2nPjM7W4D": { artist: "Salad", title: "Drink the Elixir", genre: "Britpop", year: 1997 },
  "6CPuT3FBP2TZOVg8C5Jw": { artist: "Menswear", title: "Daydreamer", genre: "Britpop", year: 1995 },
  "0LKZI4TpxJZ7Vb7f0hRH": { artist: "60ft Dolls", title: "Happy Shopper", genre: "Rock", year: 1996 },
  "Q8VkSRZqKxhDJr4XxOZL": { artist: "Kenickie", title: "Punka", genre: "Indie Rock", year: 1996 },
  "HaU0Kx9DQHXs7TqJN8x5": { artist: "S*M*A*S*H", title: "Lady Love Your C***", genre: "Punk", year: 1994 },
  "WHHBOXMUxhLaKBPvYQQ2": { artist: "Shed Seven", title: "Getting Better", genre: "Britpop", year: 1996 },
  "xUMx2gV3AXXqYlvLdj2f": { artist: "Symposium", title: "Farewell to Twilight", genre: "Indie Rock", year: 1997 },
  "9QRlkzq2xJrllJ4sO7uL": { artist: "3 Colours Red", title: "Copper Girl", genre: "Rock", year: 1997 },
  "Kj6kqHzRU6UXkDKD7nqP": { artist: "China Drum", title: "Can't Stop These Things", genre: "Rock", year: 1996 },
  "klQWKP0FTBwV9RMWkZKd": { artist: "Bis", title: "Kandy Pop", genre: "Indie Pop", year: 1996 },
  "aLdZvjj0qZOqIcNxB0fT": { artist: "Campag Velocet", title: "Vito Satan", genre: "Indie Rock", year: 1997 },
  "xOHkPPXXLOzb0T3TvmOh": { artist: "Midget", title: "All Fall Down", genre: "Rock", year: 1998 },
  "F2HZkGLRQF5VfX3tVvVr": { artist: "Silver Sun", title: "Golden Skin", genre: "Rock", year: 1997 },
  "YpH8HVLODdLRJHv5vbWj": { artist: "Heavy Stereo", title: "Sleep Freak", genre: "Rock", year: 1996 },
  "pPgUcMmHxT0LQ3p6ySWx": { artist: "Thurman", title: "I Want", genre: "Rock", year: 1996 },
  "TQUjPQLxW4TfnRkDC7Tn": { artist: "Powder", title: "Afrodisiac", genre: "Indie Rock", year: 1995 },
  "lQXQlpBuPLfVpNVPRLPO": { artist: "These Animal Men", title: "Speeed King", genre: "Punk", year: 1994 },
  "vOvOzW2cLf3RKU9B8XHL": { artist: "Done Lying Down", title: "Crocodile Milk", genre: "Rock", year: 1995 },
  "c3OEQYIxZu0O7tqO7bUU": { artist: "Drugstore", title: "El President", genre: "Alternative Rock", year: 1995 },
  "Pp7LXnZdLqLX4fLdXD7v": { artist: "Northern Uproar", title: "From a Window", genre: "Britpop", year: 1996 },
  "yQNXqRYMLQpXKJGzPXjv": { artist: "Collapsed Lung", title: "Eat My Goal", genre: "Alternative Rock", year: 1996 },
  "T2l07QXQlQLQjqqS2v7E": { artist: "Bull", title: "Love Germ", genre: "Rock", year: 1996 },
  "D0H8xmXQqpjXnTN2RWKx": { artist: "Warm Jets", title: "Never Never", genre: "Indie Rock", year: 1998 },
  "7VEJRvLf4JJzUgJ7RG7F": { artist: "Ultrasound", title: "Stay Young", genre: "Indie Rock", year: 1998 },
  "jOHrC0VLqNqVcqUKqKfC": { artist: "Gay Dad", title: "To Earth With Love", genre: "Rock", year: 1999 },
  "YKNtjt7cRBBQ1uO1l1WT": { artist: "Embrace", title: "All You Good Good People", genre: "Alternative Rock", year: 1997 },
  "BLjPzJJP8NpXQO8p0Np0": { artist: "Kula Shaker", title: "Tattva", genre: "Psychedelic Rock", year: 1996 },
  "M0TTOzNplPT1Pl0PTTMN": { artist: "Tiny Monroe", title: "Vertigo", genre: "Rock", year: 1996 },
  "NG0HOngq0QHU7OD8LHqU": { artist: "Flamingos", title: "Girlfriend", genre: "Indie Rock", year: 1996 },
  "cDqQ4JX0GcXXFpXOJJ3p": { artist: "Strangelove", title: "Living With The Human Machines", genre: "Alternative Rock", year: 1996 },
  "X22qQqM0LXMpKpK8qfXM": { artist: "Whale", title: "Hobo Humpin' Slobo Babe", genre: "Alternative Rock", year: 1994 },
  "VQjQ8jOQp4jj8jQ8QPVL": { artist: "Jack", title: "Wintercomessummer", genre: "Indie Rock", year: 1996 },
  "KcBLqLLqVq9qqB1BLVKL": { artist: "Earl Brutus", title: "Come Taste My Mind", genre: "Rock", year: 1995 },
  "TXJ7qHJ0J00JqJHJTHXX": { artist: "Dub War", title: "Strike It", genre: "Metal", year: 1995 },
  "GhNQfQJHCgQ8NQ3JNNf8": { artist: "Regular Fries", title: "Don't Be Afraid to Dream", genre: "Rock", year: 1997 },
  "GOPcpPODOLlOOPgXLGPL": { artist: "Helen Love", title: "Does Your Heart Go Boom", genre: "Indie Pop", year: 1997 },
  "nJKBvfGQpFKKpJfJBGBv": { artist: "Prolapse", title: "Autocade", genre: "Indie Rock", year: 1994 },
  "5W4W7SvKKRWvv5KKVWKR": { artist: "Quickspace", title: "Friend", genre: "Indie Rock", year: 1997 },
  "cTYHyHtI4HtIYIHYcHYt": { artist: "Paw", title: "Jessie", genre: "Rock", year: 1993 },
  "SHLdHMHDML0ddSdSHLdL": { artist: "Urusei Yatsura", title: "Fake Fur", genre: "Indie Rock", year: 1996 },
  "T1DVrKMD1T1TKrDrV1Kv": { artist: "Jolt", title: "Apathy in the UK", genre: "Rock", year: 1977 },
  "0JpQpTJvLJLJ0TpQpvpQ": { artist: "Action Pact", title: "Yet Another Dole Queue Song", genre: "Punk", year: 1983 },
  "DWpppDpLp0WpLLpppWWp": { artist: "The Boys", title: "I Don't Care", genre: "Punk", year: 1977 },
  "DggKgKxRggggxg7DxKgg": { artist: "Penetration", title: "Don't Dictate", genre: "Punk", year: 1978 },
  "xLOXVVxOXXpLLVXLXppp": { artist: "999", title: "Homicide", genre: "Punk", year: 1978 },
  "cQZKQZ0WcKWWQ0QWcKQc": { artist: "The Ruts", title: "Babylon's Burning", genre: "Punk", year: 1979 },
  "P0LnPlXnLLXlPnLPnlPl": { artist: "The Lurkers", title: "Ain't Got a Clue", genre: "Punk", year: 1977 },
  "TU0gggURgTUU0gUTRR0T": { artist: "UK Subs", title: "Stranglehold", genre: "Punk", year: 1979 },
  "RRFRLRFFLRRFRRLLLRRF": { artist: "Stiff Little Fingers", title: "Alternative Ulster", genre: "Punk", year: 1978 },
  "BBRxRRRxxRBBBBRxRBBB": { artist: "Angelic Upstarts", title: "I'm An Upstart", genre: "Punk", year: 1979 },
  "5x5555iiSiS5SSxSxxSx": { artist: "Anti-Nowhere League", title: "Streets of London", genre: "Punk", year: 1981 },
  "NRNRRRR5yyN5RyNRRR5y": { artist: "The Exploited", title: "Sex and Violence", genre: "Punk", year: 1981 },
  "l000jWlj0jjWlljllj00": { artist: "Discharge", title: "Hear Nothing See Nothing Say Nothing", genre: "Punk", year: 1982 },
  "L5CCVCLCCVCCVxVVCVLL": { artist: "GBH", title: "City Baby Attacked By Rats", genre: "Punk", year: 1982 },
  "llRNXllXlRlRlRlllNXN": { artist: "Varukers", title: "Die For Your Government", genre: "Punk", year: 1983 },
  "xXXXzXzZ5XxzzXXz5zxz": { artist: "Chaos UK", title: "Farmyard Boogie", genre: "Punk", year: 1983 },
};

async function enrichSongs() {
  console.log('Starting song enrichment process...');
  console.log(`Total songs to enrich: ${Object.keys(enrichmentData).length}`);

  let successCount = 0;
  let errorCount = 0;
  const errors = [];

  for (const [songId, data] of Object.entries(enrichmentData)) {
    try {
      const releaseDate = `${data.year}-01-01`;

      await dynamodb.update({
        TableName: 'bndy-songs',
        Key: { id: songId },
        UpdateExpression: 'SET genre = :genre, releaseDate = :releaseDate, updatedAt = :updatedAt',
        ExpressionAttributeValues: {
          ':genre': data.genre,
          ':releaseDate': releaseDate,
          ':updatedAt': new Date().toISOString()
        }
      }).promise();

      successCount++;
      console.log(`[${successCount}] Updated: ${data.artist} - ${data.title} (${data.genre}, ${data.year})`);

      // Rate limiting - small delay to avoid DynamoDB throttling
      await new Promise(resolve => setTimeout(resolve, 50));

    } catch (error) {
      errorCount++;
      errors.push({ songId, artist: data.artist, title: data.title, error: error.message });
      console.error(`ERROR updating ${data.artist} - ${data.title}:`, error.message);
    }
  }

  console.log('\n=== ENRICHMENT COMPLETE ===');
  console.log(`Successfully updated: ${successCount} songs`);
  console.log(`Errors: ${errorCount}`);

  if (errors.length > 0) {
    console.log('\nFailed songs:');
    errors.forEach(err => {
      console.log(`  - ${err.artist} - ${err.title}: ${err.error}`);
    });
  }
}

// Run the enrichment
enrichSongs()
  .then(() => {
    console.log('\nScript completed successfully!');
    process.exit(0);
  })
  .catch(error => {
    console.error('\nFatal error:', error);
    process.exit(1);
  });
