AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: BNDY Platform Serverless API - Lambda Functions + API Gateway (Redeploying)

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Environment:
      Variables:
        NODE_ENV: production

Parameters:
  Stage:
    Type: String
    Default: prod
    Description: Deployment stage (dev, staging, prod)

Resources:
  # API Gateway
  BndyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      EndpointConfiguration: EDGE
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Cookie'"
        AllowOrigin: "'https://backstage.bndy.co.uk,https://d3cewujswmjafa.cloudfront.net'"
        AllowCredentials: true

  # Venues Lambda Function
  VenuesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: venues-lambda/
      Handler: handler.handler
      MemorySize: 512
      Description: BNDY Venues API - handles /api/venues endpoints
      Role: arn:aws:iam::771551874768:role/bndy-api-instance-role
      Events:
        GetAllVenues:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /api/venues
            Method: get
        GetVenueById:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /api/venues/{id}
            Method: get
        CreateVenue:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /api/venues
            Method: post
        UpdateVenue:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /api/venues/{id}
            Method: put
        DeleteVenue:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /api/venues/{id}
            Method: delete

  # Auth Lambda Function
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth-lambda/
      Handler: handler.handler
      MemorySize: 512
      Description: BNDY Authentication API - handles OAuth and sessions
      Role: arn:aws:iam::771551874768:role/bndy-api-instance-role
      Events:
        AuthGoogle:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /auth/google
            Method: get
        AuthCallback:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /auth/callback
            Method: get
        ApiMe:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /api/me
            Method: get


  # Events Lambda Function
  EventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: events-lambda/
      Handler: handler.handler
      MemorySize: 512
      Description: BNDY Events API - handles calendar and event management
      Role: arn:aws:iam::771551874768:role/bndy-api-instance-role
      Events:
        GetPublicEvents:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /api/events
            Method: get
        CreateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /admin/events
            Method: post
        UpdateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /admin/events/{id}
            Method: put
        DeleteEvent:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /admin/events/{id}
            Method: delete
        GetBandEvents:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /admin/events/band/{bandId}
            Method: get

  # Artists Lambda Function
  ArtistsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: artists-lambda/
      Handler: handler.handler
      MemorySize: 512
      Description: BNDY Artists API - handles /api/artists endpoints
      Role: arn:aws:iam::771551874768:role/bndy-api-instance-role
      Events:
        GetAllArtists:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /api/artists
            Method: get
        GetArtistById:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /api/artists/{id}
            Method: get
        CreateArtist:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /api/artists
            Method: post
        UpdateArtist:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /api/artists/{id}
            Method: put
        DeleteArtist:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /api/artists/{id}
            Method: delete

  # Songs Lambda Function
  SongsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: songs-lambda/
      Handler: handler.handler
      MemorySize: 512
      Description: BNDY Songs API - handles /api/songs endpoints
      Role: arn:aws:iam::771551874768:role/bndy-api-instance-role
      Events:
        GetAllSongs:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /api/songs
            Method: get
        GetSongById:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /api/songs/{id}
            Method: get
        CreateSong:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /api/songs
            Method: post
        UpdateSong:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /api/songs/{id}
            Method: put
        DeleteSong:
          Type: Api
          Properties:
            RestApiId: !Ref BndyApi
            Path: /api/songs/{id}
            Method: delete

Outputs:
  BndyApi:
    Description: "API Gateway endpoint URL for BNDY API"
    Value: !Sub "https://${BndyApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"

  VenuesFunctionArn:
    Description: "Venues Lambda Function ARN"
    Value: !GetAtt VenuesFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-VenuesFunctionArn"

  AuthFunctionArn:
    Description: "Auth Lambda Function ARN"
    Value: !GetAtt AuthFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-AuthFunctionArn"

  ArtistsFunctionArn:
    Description: "Artists Lambda Function ARN"
    Value: !GetAtt ArtistsFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ArtistsFunctionArn"

  SongsFunctionArn:
    Description: "Songs Lambda Function ARN"
    Value: !GetAtt SongsFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SongsFunctionArn"